[project]
name = "django-books-04-v2"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "django>=5.1.6",
    "djangorestframework>=3.15.2",
    "mysqlclient>=2.2.7",
    "python-dotenv>=1.0.1",
]
